import Head from "next/head";
import Container from "react-bootstrap/Container";
import Card from "react-bootstrap/Card";
import CardGroup from "react-bootstrap/CardGroup";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" className="py-4 px-3 mx-auto">
        <body className="text-bg-dark">
          <Header state="about" />

          <h1 className="text-center mx-3">About</h1>

          <CardGroup className="mb-5">
            <Card className="card-custom mx-2 pt-5 mb-5">
              <Card.Img variant="top" src="environemntalismcard.jpeg" alt="Nature Scene"/>
              <Card.Header className="bg-yellow card-custom">Projects</Card.Header>
              <Card.Body className="card-fade">
                <Card.Title>FISC Study Tool</Card.Title>
                <Card.Text className="pb-5">
                  One of my proudest contributions is my FISC Study Tool. It has always been my dream to work in the environmental or ecological sector, and one of the first skills employers look for it a FISC certification. Being able to identify native plants while conducting a survey is vital, as an ecological consultant's credibility often hinges on their ability to accurately identify flora in the field. The FISC Study Tool is designed to help aspiring consultants prepare for the FISC exam by providing a comprehensive database of plant species, along with interactive quizzes and study materials. By making this tool freely available, I hope to support others in achieving their certification and advancing their careers in environmental consultancy.
                </Card.Text>
              </Card.Body>
            </Card>
            <Card className="card-custom">
              <Card.Img variant="left" src="animalcard.jpeg" alt="Chipmunk"/>
              <Card.Header className="bg-yellow card-custom">Ethos</Card.Header>
              <Card.Body style={{backgroundColor: 'white'}}>
                <Card.Title>Environmentalist</Card.Title>
                <Card.Text className="pb-5">
                  I am an environmentalist at heart who believes in the power of technology to drive positive change. However, most of that change depends on the people driving it. My goal is to use my skills to create applications that empower individuals and communities to make informed decisions and take meaningful action towards a more sustainable future. I refrain from using AI due to its impact on the environment and potential job losses it may cause. Instead, I focus on leveraging my expertise in web development to build tools that facilitate environmental conservation and awareness. By combining my passion for the environment with my technical skills, I aim to contribute to a more sustainable world.
                </Card.Text>
              </Card.Body>
            </Card>
            <Card className="card-custom mx-2 pt-5 mb-5">
              <Card.Img variant="left" src="treecard.jpeg" alt="Tree with Bird"/>
              <Card.Header className="bg-yellow card-custom">Sources</Card.Header>
              <Card.Body className="card-fade">
                <Card.Title>Contributions</Card.Title>
                <Card.Text className="pb-5">
                  This tool wouldn't have been possible without the BISC Online Plant Atlas 2020, which provided the essential data needed to build the database. I am deeply grateful to the BSBI for making this information accessible to the public, as it has enabled me to create a resource that can benefit many aspiring ecological consultants. By leveraging this data, I have been able to develop a tool that not only aids in exam preparation but also promotes greater awareness and appreciation of plant biodiversity.
                </Card.Text>
              </Card.Body>
            </Card>
          </CardGroup>

          <Footer />
        </body>
      </Container>
    </>
  );
}