import Head from "next/head";
import Container from "react-bootstrap/Container";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import CVDownload from "@/components/CVDownload";
import { useForm, ValidationError } from "@formspree/react";

export default function Home() {
  const [state, handleSubmit] = useForm("contact-form");

  if (state.succeeded) {
    return <p>Thanks for your submission!</p>;
  }

  return (
    <>
      <Head>
        <title>Bootstrap w/ React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        as="section"
        className="text-bg-dark text-center index-body background-image"
      >
        <Header state="projects" />

        <Container as="main" className="py-4 px-3 mx-auto">
          <h1>Welcome to my portfolio website</h1>
          <p className="fst-italic fs-sm yellow">
            built utilising ReactJS, NextJS, and Bootstrap
          </p>
          <CVDownload />
        </Container>
      </Container>

      <Container as="section" className="section" id="about">
        <Container className="container">
          <div className="col-lg-12">
            <div className="text-center about-detail mx-auto mt-5">
              <h3 className="mb-3">
                Hello! <span className="fw-bold yellow">I'M Kizzy Sinar.</span>
              </h3>
              <ul className="mb-0 list-inline text-center about-work">
                <li className="list-inline-item me-0 text-muted">
                  UI/UX Designer
                </li>
                <li className="list-inline-item me-0 text-muted">
                  Photographer
                </li>
                <li className="list-inline-item me-0 text-muted">Devloper</li>
              </ul>
              <p className="text-muted mt-3">
                It is a long established fact that a reader will be distracted
                by the readable content of a page when looking at its layout.The
                point of using Lorem Ipsum is that it has a more-or-less normal
                distribution of letters, as opposed to using 'Content here,
                content here', making it look like readable English.
              </p>
            </div>
          </div>
          <Container className="row mt-5">
            <Container className="col-lg-6">
              <div className="progress-bars skill-custom">
                <div className="clearfix">
                  <div className="text-dark fw-bold float-left">
                    Full-Stack Development
                  </div>
                  <div className="text-muted float-right">85%</div>
                </div>
                <div className="progress">
                  <div
                    className="progress-bar"
                    role="progressbar"
                    style={{ width: "85%" }}
                  ></div>
                </div>
                <div className="clearfix">
                  <div className="text-dark fw-bold float-left">Frontend</div>
                  <div className="text-muted float-right">75%</div>
                </div>
                <div className="progress">
                  <div
                    className="progress-bar"
                    role="progressbar"
                    style={{ width: "75%" }}
                  ></div>
                </div>
                <div className="clearfix">
                  <div className="text-dark fw-bold float-left">Backend</div>
                  <div className="text-muted float-right">55%</div>
                </div>
                <div className="progress">
                  <div
                    className="progress-bar"
                    role="progressbar"
                    style={{ width: "55%" }}
                  ></div>
                </div>
              </div>
            </Container>
            <Container className="col-lg-6">
              <div className="progress-bars skill-custom">
                <div className="clearfix">
                  <div className="text-dark fw-bold float-left">HTML</div>
                  <div className="text-muted float-right">90%</div>
                </div>
                <div className="progress">
                  <div
                    className="progress-bar"
                    role="progressbar"
                    style={{ width: "90%" }}
                  ></div>
                </div>
                <div className="clearfix">
                  <div className="text-dark fw-bold float-left">CSS</div>
                  <div className="text-muted float-right">87%</div>
                </div>
                <div className="progress">
                  <div
                    className="progress-bar"
                    role="progressbar"
                    style={{ width: "87%" }}
                  ></div>
                </div>
                <div className="clearfix">
                  <div className="text-dark fw-bold float-left">ReactJS</div>
                  <div className="text-muted float-right">75%</div>
                </div>
                <div className="progress">
                  <div
                    className="progress-bar"
                    role="progressbar"
                    style={{ width: "75%" }}
                  ></div>
                </div>
              </div>
            </Container>
          </Container>
        </Container>
      </Container>

      <Container as="section" className="section freelance-background-image ">
        <div className="bg-overlay"></div>
        <div className="col-lg-12">
          <div className="text-center text-white">
            <h1 className="tsh-l">I Am Available For Freelance Work.</h1>
            <p className="tsh-s">
              If you are a charity or environmental agency, please get in touch.
            </p>
          </div>
        </div>
      </Container>

      <Container as="section" className="section " id="contact">
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-lg-12">
              <div className="text-center mx-auto section-main-title">
                <h2>
                  Get In <span className="fw-bold yellow">Touch</span>
                </h2>
                <div className="main-title-border">
                  <i className="mdi mdi-asterisk"></i>
                </div>
                <p className="text-muted mx-auto mt-2">
                  Please use the form below, or contact me via my details on the
                  left.
                </p>
              </div>
            </div>
          </div>
          <div className="row mt-4 pt-4">
            <div className="col-lg-4">
              <div className="text-center mt-4">
                <div>
                  <span className="material-symbols-rounded fs-1">mail</span>
                </div>
                <div className="mt-2">
                  <p className="mb-0 fw-bold">Email Me At</p>
                  <p className="text-muted">kizzysinar@gmail.com</p>
                </div>
              </div>
            </div>
            <Container className="col-lg-8">
              <div className="contact_form">
                <div id="message"></div>
                <form
                  name="contact-form"
                  id="contact-form"
                  onSubmit={handleSubmit}
                >
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="form-group mt-2 mb-3">
                        <label htmlFor="name" className="fw-bold mb-2">
                          Name
                        </label>
                        <input
                          name="name"
                          id="name"
                          type="text"
                          className="form-control"
                          placeholder="Your name..."
                          required
                        />
                      </div>
                      <ValidationError prefix="Name" field="name" errors={state.errors} />
                    </div>
                    <div className="col-lg-6">
                      <div className="form-group mt-2 mb-3">
                        <label htmlFor="email" className="fw-bold mb-2">
                          Email address
                        </label>
                        <input id="email" 
                          type="email" 
                          name="email"
                          className="form-control"
                          placeholder="Your email..." 
                          required
                        />
                        <ValidationError prefix="Email" field="email" errors={state.errors} />
                      </div>
                    </div>
                    <div className="col-lg-12">
                      <div className="form-group mt-2 mb-3">
                        <label htmlFor="subject" className="fw-bold mb-2">
                          Subject
                        </label>
                        <input
                          type="text"
                          className="form-control"
                          id="subject"
                          placeholder="Your Subject.."
                        />
                        <ValidationError prefix="Subject" field="subject" errors={state.errors} />
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-lg-12">
                      <div className="form-group mt-2 mb-3">
                        <label htmlFor="messsage" className="fw-bold mb-2">
                          Message
                        </label>
                        <textarea
                          name="messsage"
                          id="messsage"
                          rows={4}
                          className="form-control"
                          placeholder="Your message..."
                        ></textarea>
                        <ValidationError prefix="Message" field="message" errors={state.errors} />
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-sm-12 text-right">
                      <button 
                        type="submit" 
                        disabled={state.submitting}
                        id="submit"
                        name="send"
                        className="submitBnt btn btn-custom"
                      >
                        Send Message
                      </button>
                      <ValidationError errors={state.errors} />
                      <div id="simple-msg"></div>
                    </div>
                  </div>
                </form>
              </div>
            </Container>
          </div>
        </div>
      </Container>

      <Footer />
    </>
  );
}
