import Head from "next/head";
import Container from "react-bootstrap/Container";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container as="main" className="py-4 px-3 mx-auto">
        <body className="text-bg-dark text-center">
          <Header state="projects" />

          <h1>Projects</h1>
          
          <p>Coming soon!</p>

          <Footer />
        </body>
      </Container>
    </>
  );
}
